name: Cookie

on:
  workflow_call:

env:
  # Many color libraries just need this to be set to any value, but at least
  # one distinguishes color depth, where "3" -> "256-bit color".
  FORCE_COLOR: 3

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint all
        run: pipx run nox -s 'lint'

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
        runs-on: [ubuntu-latest, windows-latest, macos-14]

        include:
          - python-version: pypy-3.9
            runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Setup uv
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"

      - name: Install nox
        run: uv pip install nox

      - name: Test scikit-build
        run: nox -s 'tests(skbuild, novcs)' -s 'tests(skbuild, vcs)'

      - name: Test maturin
        run: nox -s 'tests(maturin, novcs)'

      - name: Test hatch
        run: nox -s 'tests(hatch, novcs)' -s 'tests(hatch, vcs)'

      - name: Compare copier template generation
        run: nox -s compare_copier

      - name: Compare cruft template generation
        run: nox -s compare_cruft

  nox:
    name: Check included Noxfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Setup uv
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"

      - name: Install nox
        run: uv pip install nox

      - name: Test scikit-build
        run: |
          nox -s 'nox(skbuild, vcs)'
          nox -s 'nox(skbuild, vcs)' -- docs

      - name: Test maturin
        run: |
          nox -s 'nox(maturin, novcs)'
          nox -s 'nox(maturin, novcs)' -- docs

      - name: Test hatch
        run: |
          nox -s 'nox(hatch, vcs)'
          nox -s 'nox(hatch, vcs)' -- docs

  dist:
    name: Distribution build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build sdist and wheel
        run: pipx run nox -s dist

      - name: Show results
        run: ls -l dist

      - uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: dist

  pass:
    if: always()
    needs: [dist, nox, checks, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
