name: Cookie

on:
  workflow_call:

env:
  FORCE_COLOR: 3

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint all
        run: pipx run nox -s 'lint'

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

        include:
          - python-version: pypy-3.9
            runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install nox
        run: pip install nox

      - name: Test scikit-build
        run: nox -s 'tests(skbuild)'

      - name: Test maturin
        run: nox -s 'tests(maturin)'

      - name: Test hatch
        run: nox -s 'tests(hatch)'

      - name: Compare copier template generation
        run: nox -s compare_copier

      - name: Compare cruft template generation
        run: nox -s compare_cruft

  nox:
    name: Check included Noxfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test scikit-build
        run: |
          pipx run nox -s 'nox(skbuild)'
          pipx run nox -s 'nox(skbuild)' -- docs

      - name: Test maturin
        run: |
          pipx run nox -s 'nox(maturin)'
          pipx run nox -s 'nox(maturin)' -- docs

      - name: Test hatch
        run: |
          pipx run nox -s 'nox(hatch)'
          pipx run nox -s 'nox(hatch)' -- docs

  dist:
    name: Distribution build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build sdist and wheel
        run: pipx run nox -s dist

      - name: Show results
        run: ls -l dist

      - uses: actions/upload-artifact@v3
        with:
          path: dist

  pass:
    if: always()
    needs: [dist, nox, checks, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
